version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database",  "mysql://root:root@tcp(mysql:3306)/orders", "up" ]
    volumes:
      - ./internal/infra/database/sql/migrations:/migrations
    depends_on:
      mysql:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  ordersystem:
    build: .
    container_name: ordersystem
    volumes:
      - .:/app
    working_dir: /app/cmd/ordersystem
    command: go run main.go wire_gen.go
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 8000:8000
      - 50051:50051
      - 8080:8080
    restart: always